### ISSUE TITLE
nvidia installer timeout

### ISSUE THREAD

**Issue by dolphinoracle** [smxi/sgfxi#8]
sgfxi is timing out on installing nvidia drivers from nvidia.

some info about ftp site going down may be related.  Here's  link to a post on the mx linux forum with more info.

https://forum.mxlinux.org/viewtopic.php?p=412875#p412875

Discontinuing FTP access to download.nvidia.com

Due to an infrastructure change, FTP access to NVIDIA driver, source code, and documentation downloads is no longer available at ftp://download.nvidia.com. This change took place on April 28th, 2017.

The content currently hosted at ftp://download.nvidia.com will continue to be available at http://download.nvidia.com, and is now additionally available at https://download.nvidia.com.

NVIDIA recommends that any users previously downloading content from ftp://download.nvidia.com switch to using HTTPS instead, or HTTP if HTTPS support is not available.

Daniel Dadap
NVIDIA Linux Graphics

**Comment by smxi** [comment]
This has been corrected in the new inxi, switched to https, checked it and seems to work fine. Thanks for posting this issue. I just tested this a few days ago and it was working, must have been before the 28th I guess.
